services:
  elasticsearch:
    image: bitnami/elasticsearch:latest
    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - elk-network
  kibana:
    image: bitnami/kibana:latest
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://localhost:9200
    ports:
      - "5601:5601"
    networks:
      - elk-network
#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  elk-network:
    driver: bridge
